package com.myfirstsoap.activate;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2018-06-10T19:28:21.434+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://myfirstsoap.com/activate/", name = "Activation")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Activation {

    @WebMethod(action = "http://myfirstsoap.com/activate/activationOperation")
    @WebResult(name = "activationResponse", targetNamespace = "http://myfirstsoap.com/activate/", partName = "parameters")
    public ActivationResponse activationOperation(
        @WebParam(partName = "parameters", name = "activationRequest", targetNamespace = "http://myfirstsoap.com/activate/")
        ActivationRequest parameters
    );
}
